version: '2.1'

services:
  redis:
    image: autopilotpattern/redis:3.2.8-r1.0.0
    mem_limit: 512m
    restart: always
    environment:
      - CONSUL=consul
    links:
      - consul:consul
    expose:
      - 6379
      - 26379
    network_mode: bridge

  consul:
    image: autopilotpattern/consul:0.7.2-r0.8
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 1
        -config-dir=/etc/consul
        -ui-dir /ui
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    network_mode: bridge
